### ISSUE TITLE
Extend Get() to receive average for the last x datapoints

### ISSUE THREAD

**Issue by dojo90** [AlexandreHiroyuki/MovingAverage_ArduinoLibrary#24]
I would like to determine the average of the last 30 values. In parallel, I would like the average of the last 10 values.
To achieve this, I would have to create two `MovingAverage` and feed them with the same data.

```
MovingAverage<unsigned int> slowSensor(30);
MovingAverage<unsigned int> fastSensor(10);

slowSensor.push(sensorData);
fastSensor.push(sensorData);
```

By extending the `get()` with an optional parameter, it would be possible to solve this issue with one `MovingAverage` object

for example:

```
int slowSensorMovingAvg = slowSensor.get(); // average of 30 datapoints
int fastSensorMovingAvg = slowSensor.get(10); // average of 10 datapoints
```

**Comment by AlexandreHiroyuki** [comment]
Currently, on commit [55d5864c37f3a4d0e225d63ed6e352804902ea00](https://github.com/AlexandreHiroyuki/MovingAverage_ArduinoLibrary/commit/55d5864c37f3a4d0e225d63ed6e352804902ea00), I added a method to calculate the average by adding the requested data points every time it's called.
Although, I'm working on a solution to calculate specific average sizes of the same array more efficiently. It's just an experiment, but I hope it improves the performance and usability, which were the two focuses I thought of when creating this library.

**Comment by Amorim33** [comment]
I will work on this!

**Comment by AlexandreHiroyuki** [comment]
#30
