### ISSUE TITLE
Average of an incomplete filled MovingAverage object

### ISSUE THREAD

**Issue by dojo90** [AlexandreHiroyuki/MovingAverage_ArduinoLibrary#25]
By default all positions will be initialized with 0. If I create a `MovingAverage<unsigned int> fooAvg(10);` and fill it with only 5 values, then the average should also only be calculated from these 5 values.

**Comment by AlexandreHiroyuki** [comment]
Thank you for pointing out the issue. Since this library was born as a side project, I didn't pay attention to this problem because it didn't affect the main project. I will work on it, also be free to make a Pull Request if you think of a better solution.

**Comment by AlexandreHiroyuki** [comment]
The bug is solved. Now the average is divided by the number of data points added. Not by the array size.
